export const tagTypes = {
  GARDENS: "Gardens",
  Property: "Property",
  PropertyOverview: "PropertyOverview",
  PropertyListing: "PropertyListing",
  Apartments: "Apartments",
  Commissions: "Commissions",
  Commission: "Commission",
  Overview: "Overview",
  TrendingChart: "TrendingChart",
  AgentChart: "AgentChart",
  AuditTrail: "AuditTrail",
  Configurations: "Configurations",
  CommissionConfig: "CommissionConfig",
  Land: "Land",
  Sale: "Sale",
  Rent: "Rent",
  User: "User",
  UserCount: "UserCount",
  RoleStat: "RoleStat",
  Role: "Role",
  RolePermissions: "RolePermissions",
  Users: "Users",
  UserPub: "UserPub",
  UserPubWithRole: "UserPubWithRole",
  LandListing: "LandListing",
  LandListingWithCommission: "LandListingWithCommission",
};
